[package]
name = "treenity"
version = "0.1.0"
authors = ["Tigran Bayburtsyan <tigran@bayburtsyan.com>"]

[dependencies]
mio = "0.6.0"
num = "0.1"
byteorder = "0.5"
num_cpus = "1.1"
rmp-serde = "0.10"
serde = "0.8.18"
