[tree_node]
[tree_node.tree1]
name="tree1"
tree_port=8888
tree_ip="15.15.15.15"
tags=["sv"]
groups=["dev"]
childs=["tree2"]

[tree_node.tree2]
name="tree2"
tree_port=8888
tree_ip="15.15.15.16"
tags=["sv"]
groups=["qa"]
childs=["tree3"]

[tree_node.tree3]
name="tree3"
tree_port=8888
tree_ip="15.15.15.17"
tags=["sv"]
groups=["prod"]
childs=[]