[ssh]
[ssh.tree1]
host="tree-node-1.cloudapp.net"
port=22
username="tree"

[ssh.tree2]
host="tree-node-2.cloudapp.net"
port=22
username="tree"

[ssh.tree3]
host="tree-node-3.cloudapp.net"
port=22
username="tree"

[ssh.tree4]
host="tree-node-4.cloudapp.net"
port=22
username="tree"

[ssh.tree5]
host="tree-node-5.cloudapp.net"
port=22
username="tree"

[ssh.tree6]
host="tree-node-6.cloudapp.net"
port=22
username="tree"

[ssh.tree7]
host="tree-node-7.cloudapp.net"
port=22
username="tree"

[ssh.tree8]
host="tree-node-8.cloudapp.net"
port=22
username="tree"

[ssh.tree9]
host="tree-node-9.cloudapp.net"
port=22
username="tree"

[ssh.tree10]
host="tree-node-10.cloudapp.net"
port=22
username="tree"