[ssh]
[ssh.php_server1]
host="192.168.107.15"
port="22"
username="root"

[ssh.php_server2]
host="192.168.107.18"
port="22"
username="root"

[ssh.mysql_server]
host="192.168.107.16"
port="22"
username="root"
