[tree_node]
[tree_node.tree1]
name="tree1"
tree_port=8888
tree_ip="tree-node-1.cloudapp.net"
tags=[]
groups=["backend"]
childs=["tree2", "tree4"]

[tree_node.tree2]
name="tree2"
tree_port=8888
tree_ip="tree-node-2.cloudapp.net"
tags=[]
groups=[]
childs=["tree3"]

[tree_node.tree3]
name="tree3"
tree_port=8888
tree_ip="tree-node-3.cloudapp.net"
tags=[]
groups=[]
childs=[]

[tree_node.tree4]
name="tree4"
tree_port=8888
tree_ip="tree-node-4.cloudapp.net"
tags=[]
groups=[]
childs=["tree6", "tree7"]

[tree_node.tree5]
name="tree5"
tree_port=8888
tree_ip="tree-node-5.cloudapp.net"
tags=[]
groups=[]
childs=["tree8"]

[tree_node.tree6]
name="tree6"
tree_port=8888
tree_ip="tree-node-6.cloudapp.net"
tags=[]
groups=[]
childs=[]

[tree_node.tree7]
name="tree2"
tree_port=8888
tree_ip="tree-node-7.cloudapp.net"
tags=[]
groups=[]
childs=["tree9", "tree10"]

[tree_node.tree8]
name="tree2"
tree_port=8888
tree_ip="tree-node-8.cloudapp.net"
tags=[]
groups=[]
childs=[]

[tree_node.tree9]
name="tree2"
tree_port=8888
tree_ip="tree-node-9.cloudapp.net"
tags=[]
groups=[]
childs=[]

[tree_node.tree10]
name="tree2"
tree_port=8888
tree_ip="tree-node-10.cloudapp.net"
tags=[]
groups=[]
childs=[]