[tree_node]
[tree_node.tree1]
name="tree1"
tree_port=8888
tree_ip="127.0.0.1"
tags=["php", "prod"]
groups=["backend"]
childs=["tree2"]

[tree_node.tree2]
name="tree2"
tree_port=8887
tree_ip="127.0.0.1"
tags=["php"]
groups=["backend"]
childs=[]